### ISSUE TITLE
[Download failed] Not Found

### ISSUE THREAD

**Issue by wernerml** [danguilherme/spotivy#34]
Hello, I've just installed everything, updated all git dependencies
Windows 10 Enterprise LTSC

spotivy appears to be working, (configured YouTube API + Spotify App Client ID + Secret)
but, I can't download any video....

if I try:   spotivy track 3SCsueX2bZdbEzRtKOCEyT
I get: `[Download failed] Not Found`

if I try:   spotivy playlist wernerml 6ehHwU2hpFIqzsrdDokJKv (which is a a playlist with 2 videos, 1 of them being the same 3SCsueX2bZdbEzRtKOCEyT as in command above)
I get: 

```
   [Downloading playlist] Vacines
        [Download failed] Cannot read properties of null (reading 'id')
        [Download failed] Cannot read properties of null (reading 'id')
```
(which seems to be 2 error messages for the 2 videos of the playlist....

is this project outdated ? working ?
Thank you!

**Comment by danguilherme** [comment]
Hi there, thanks for opening the issue!

The project should be working fine, but I see that the track you're trying to download is actually a podcast episode, and those are not supported by the tool.
Maybe it could be implemented, as long as these episodes can be also found on YouTube, because that's where the media is downloaded from (not from Spotify).

Related issue: #33
